window.SOCCER_DATA = {
  axes: [
    { id: "vision", name: "读局", low: "先出脚", high: "先看见", description: "你会先观察局面，再选择怎么接管它。" },
    { id: "initiative", name: "担当", low: "共同解题", high: "主动扛责", description: "你更习惯把关键一球交给谁来处理。" },
    { id: "creativity", name: "创造", low: "稳定执行", high: "即兴变招", description: "你面对熟悉局面时，是守住节奏还是改写它。" },
    { id: "teamplay", name: "协作", low: "个人突破", high: "让全队更好", description: "你会优先相信自己的强项，还是队友之间的连接。" },
    { id: "grit", name: "韧性", low: "调整节奏", high: "越战越勇", description: "压力升高时，你会如何把自己带回比赛。" }
  ],
  questions: [
    { axis: "vision", kicker: "读局能力 · 01", title: "比赛来到最后十分钟，比分仍然咬得很紧。球传到你脚下——", prompt: "你最自然的第一步是什么？", answers: ["先带球冲出空当，边跑边看", "抬头找一个最熟悉的配合", "看清防线重心，再选一条缝", "停半拍，把队友都带进局面"], values: [-2, -1, 2, 1] },
    { axis: "vision", kicker: "读局能力 · 02", title: "对手压得很靠前，场上空间忽然变得很窄。", prompt: "你通常怎么找出路？", answers: ["靠第一感觉快速做决定", "先把球稳住，等队形变化", "观察对手哪一侧先失去平衡", "看看谁跑出了最值得信任的位置"], values: [-2, -1, 2, 1] },
    { axis: "initiative", kicker: "担当方式 · 01", title: "点球大战，你排在队友后面。前两位都没有罚进。", prompt: "轮到你时，你会——", answers: ["照原来的习惯踢，不加戏", "跟队友确认一下门将的方向", "主动要球，也主动承担结果", "先稳住呼吸，再把注意力放回动作"], values: [1, -1, 2, -2] },
    { axis: "initiative", kicker: "担当方式 · 02", title: "你在一场关键比赛里刚刚犯了错，球队还落后一球。", prompt: "接下来最像你的做法是？", answers: ["主动要球，把比赛重新抓回来", "和队友说清楚下一步怎么补位", "先做一件最简单可靠的事", "不急着证明自己，继续读比赛"], values: [2, 1, -1, -2] },
    { axis: "creativity", kicker: "临场创造 · 01", title: "训练场上没有教练指令，也没有固定套路。", prompt: "你最享受的部分是什么？", answers: ["把基本动作重复到足够稳定", "试一个昨天才想到的新动作", "和队友临时发明一套配合", "来一场小比赛，看灵感会不会出现"], values: [-2, 2, 1, 1] },
    { axis: "creativity", kicker: "临场创造 · 02", title: "比赛陷入僵局，熟悉的打法被对手看穿了。", prompt: "你倾向于怎么改？", answers: ["增加变化，做一件对手猜不到的事", "继续执行，但把每个细节做好", "先观察，再挑一个小地方改变", "换一种节奏，让队友重新找到空间"], values: [2, -2, 1, 1] },
    { axis: "teamplay", kicker: "团队默契 · 01", title: "赛季结束后，队友会怎样描述你？", prompt: "哪个评价最让你觉得是自己？", answers: ["关键时刻敢于站出来", "让大家踢得更轻松的人", "能凭个人能力改变局面的人", "再难的局面也不会放弃的人"], values: [ -1, 2, -2, 1] },
    { axis: "teamplay", kicker: "团队默契 · 02", title: "一位新队友第一次加入训练，显得有些拘谨。", prompt: "你可能会先做什么？", answers: ["把球传给他，让他更快融入", "跟他聊聊习惯的踢法", "拿出自己的本事，让他知道可以信任你", "照平常节奏训练，让他慢慢适应"], values: [2, 2, -2, -1] },
    { axis: "grit", kicker: "压力与韧性 · 01", title: "刚刚输掉一场你准备了很久的比赛。", prompt: "你的恢复方式更像哪一个？", answers: ["先睡一晚，第二天再认真复盘", "很快开始计划下一场怎么赢", "拉上队友一起找出错在哪里", "给自己一点空间，再慢慢找回节奏"], values: [-1, 2, 1, -2] },
    { axis: "grit", kicker: "压力与韧性 · 02", title: "越接近终场，压力越大；全场都在看最后一次进攻。", prompt: "压力对你的影响更接近——", answers: ["提醒自己一步一步做好", "让我比平时更专注", "越紧张越想主动要球", "先帮团队稳住，再等机会"], values: [-1, 1, 2, -2] }
  ],
  players: [
    { id: "messi", name: "梅西", english: "LIONEL MESSI", number: "10", category: "现役球星", archetype: "静水流深的创造者", summary: "你擅长先读懂场面，再用一个看似轻巧的决定改变走向。你不一定急着成为焦点，却总知道何时该让比赛经过自己。", tags: ["读场敏锐", "精准克制", "关键一传"], profile: [98, 72, 92, 90, 88], file: "Lionel Messi Argentina v Egypt 7 July 2026-130 (cropped).jpg", credit: "Bryan Berlin / WikiPortraits · CC BY-SA 4.0", creditUrl: "https://creativecommons.org/licenses/by-sa/4.0/" },
    { id: "ronaldo", name: "克里斯蒂亚诺·罗纳尔多", english: "CRISTIANO RONALDO", number: "7", category: "现役球星", archetype: "目标感拉满的终结者", summary: "你愿意把目标讲清楚，也愿意为它多走一步。压力来了，你更像是那个站出来要球的人；持续打磨自己，是你最稳定的底气。", tags: ["强烈担当", "自我驱动", "关键时刻"], profile: [78, 99, 74, 73, 99], file: "Cristiano Ronaldo Croatia v Portugal 2 July 2026-154(cropped).jpg", credit: "Bryan Berlin / WikiPortraits · CC BY 4.0", creditUrl: "https://creativecommons.org/licenses/by/4.0/" },
    { id: "mbappe", name: "姆巴佩", english: "KYLIAN MBAPPÉ", number: "10", category: "现役球星", archetype: "一脚提速的破局先锋", summary: "你发现机会时会很快行动，不习惯让好的窗口白白过去。你能把速度、判断和目标感连起来，带着身边的人一起往前。", tags: ["果断启动", "向前意识", "大场面"], profile: [81, 94, 88, 78, 92], file: "Kylian Mbappe - France v Norway - 26 June 2026 (cropped).jpg", credit: "Bryan Berlin / WikiPortraits · CC BY-SA 4.0", creditUrl: "https://creativecommons.org/licenses/by-sa/4.0/" },
    { id: "haaland", name: "哈兰德", english: "ERLING HAALAND", number: "9", category: "现役球星", archetype: "把机会变成进球的人", summary: "你更相信清晰的目标、直接的动作和稳定的执行。对你来说，机会一旦出现就值得全力追上；简单有效，比花哨更重要。", tags: ["目标清晰", "行动直接", "专注到底"], profile: [72, 97, 67, 74, 93], file: "Erling Haaland Morocco v Norway 7 June 2026-164.jpg", credit: "Bryan Berlin / WikiPortraits · CC BY-SA 4.0", creditUrl: "https://creativecommons.org/licenses/by-sa/4.0/" },
    { id: "yamal", name: "亚马尔", english: "LAMINE YAMAL", number: "19", category: "现役球星", archetype: "越踢越敢的灵感派", summary: "你保留着对新鲜事物的好奇，遇到空间时敢于做一点自己的选择。你不怕尝试，也能把个人的灵光变成队友看得见的机会。", tags: ["灵感充足", "从容大胆", "默契创造"], profile: [88, 80, 99, 87, 84], file: "Lamine Yamal France v Spain 7.24.26-142 (cropped).jpg", credit: "Bryan Berlin / WikiPortraits · CC BY-SA 4.0", creditUrl: "https://creativecommons.org/licenses/by-sa/4.0/" },
    { id: "vinicius", name: "维尼修斯", english: "VINÍCIUS JÚNIOR", number: "7", category: "现役球星", archetype: "带着火花向前的人", summary: "你不愿让对手轻易定义局面。面对压力，你会继续做自己擅长的事；你的活力会感染队友，也会让比赛重新变得有趣。", tags: ["敢于突破", "能量外放", "越压越勇"], profile: [74, 88, 98, 82, 94], file: "Vinicius Junior Brazil V Morocco 13 June 2026-94 (cropped).jpg", credit: "Bryan Berlin / WikiPortraits · CC BY-SA 4.0", creditUrl: "https://creativecommons.org/licenses/by-sa/4.0/" },
    { id: "salah", name: "萨拉赫", english: "MOHAMED SALAH", number: "11", category: "现役球星", archetype: "安静高效的稳定输出者", summary: "你不需要过多铺陈来证明自己。专注、持续和准确的选择让你长期保持影响力；机会出现时，你能用直接的行动交出结果。", tags: ["长期专注", "高效执行", "稳定输出"], profile: [84, 95, 81, 86, 96], file: "Mohamed Salah Argentina v Egypt 7 July 2026-161 (cropped).jpg", credit: "Bryan Berlin / WikiPortraits · CC BY-SA 4.0", creditUrl: "https://creativecommons.org/licenses/by-sa/4.0/" },
    { id: "de-bruyne", name: "德布劳内", english: "KEVIN DE BRUYNE", number: "17", category: "现役球星", archetype: "看见下一拍的组织者", summary: "你常能比别人早一步发现局面将如何展开。判断、传递和执行在你这里连成一件事，身边的人也因此更容易找到发挥空间。", tags: ["提前读局", "创造机会", "团队连接"], profile: [98, 88, 95, 97, 90], file: "Kevin De Bruyne USMNT v Belgium Mar 28 2026-133.jpg", credit: "Bryan Berlin / WikiPortraits · CC BY-SA 4.0", creditUrl: "https://creativecommons.org/licenses/by-sa/4.0/" },
    { id: "pele", name: "贝利", english: "PELÉ", number: "10", category: "传奇球星", archetype: "让团队更完整的王者", summary: "你兼具强烈的个人信念和照顾整体的能力。你喜欢成为可以信赖的核心，也愿意把自己的能量分给团队，让大家一起变得更好。", tags: ["领袖气场", "全面视野", "团队荣誉"], profile: [92, 96, 91, 96, 97], file: "Pele.jpg", credit: "Ralph Alswang / U.S. National Archives · Public domain", creditUrl: "https://creativecommons.org/publicdomain/mark/1.0/" },
    { id: "maradona", name: "马拉多纳", english: "DIEGO MARADONA", number: "10", category: "传奇球星", archetype: "不按剧本走的破局者", summary: "你对自由和表达有强烈需要，遇到卡住的局面会想办法另辟蹊径。你知道自己想要什么，也能在高压中把复杂事情变简单。", tags: ["天生创造", "强烈表达", "逆境不退"], profile: [88, 98, 100, 84, 100], file: "Diego Maradona.jpg", credit: "Armando Tovar · Wikimedia Commons / CC BY 2.0", creditUrl: "https://creativecommons.org/licenses/by/2.0/" },
    { id: "zidane", name: "齐达内", english: "ZINÉDINE ZIDANE", number: "5", category: "传奇球星", archetype: "从容掌控节奏的艺术家", summary: "越是复杂的局面，你越愿意先让自己慢下来。你讲究时机、质量与分寸，常常用一次准确的处理，给全队找回清楚的方向。", tags: ["冷静读局", "技术细腻", "举重若轻"], profile: [99, 85, 93, 89, 87], file: "Zidane BW.jpg", credit: "Walterlan Papetti · Wikimedia Commons / CC BY-SA 4.0", creditUrl: "https://creativecommons.org/licenses/by-sa/4.0/" },
    { id: "ronaldinho", name: "罗纳尔迪尼奥", english: "RONALDINHO", number: "10", category: "传奇球星", archetype: "把快乐踢进比赛的人", summary: "你相信热爱本身就有力量。你敢试、会玩，也愿意用轻松的气氛帮助团队打开局面；创造对你来说不是任务，而是享受。", tags: ["享受过程", "灵感涌现", "感染力强"], profile: [85, 76, 100, 93, 82], file: "Ronaldinho 72.jpg", credit: "Bollywood Hungama · Wikimedia Commons / CC BY 3.0", creditUrl: "https://creativecommons.org/licenses/by/3.0/" },
    { id: "ronaldo-nazario", name: "罗纳尔多·纳扎里奥", english: "RONALDO NAZÁRIO", number: "9", category: "传奇球星", archetype: "一瞬间改写局面的猎手", summary: "你会把注意力放在最关键的机会，不喜欢为了复杂而复杂。局面真正打开时，你能快速做决定，并把计划变成结果。", tags: ["直觉敏锐", "行动果断", "强力收尾"], profile: [77, 96, 92, 75, 96], file: "Ronaldo.jpeg", credit: "Antônio Cruz / Agência Brasil · CC BY 3.0 BR", creditUrl: "https://creativecommons.org/licenses/by/3.0/br/deed.en" },
    { id: "beckham", name: "贝克汉姆", english: "DAVID BECKHAM", number: "7", category: "传奇球星", archetype: "把团队连起来的传球手", summary: "你总在留意下一步怎样发生。准备、耐心和沟通是你的长项；一旦找到合适的路线，你会相信团队配合能够把它送到位。", tags: ["计划周全", "传递精准", "稳定可靠"], profile: [97, 86, 80, 99, 89], file: "David Beckham 2012.jpg", credit: "Kunal Shah · Wikimedia Commons / CC BY 2.0", creditUrl: "https://creativecommons.org/licenses/by/2.0/" },
    { id: "beckenbauer", name: "贝肯鲍尔", english: "FRANZ BECKENBAUER", number: "5", category: "传奇球星", archetype: "从后场看见全局的领袖", summary: "你善于从整体出发安排下一步，遇到压力时保持清晰，也愿意承担带领团队的责任。你的影响力常来自判断和从容。", tags: ["全局视野", "从容担当", "防守组织"], profile: [99, 92, 88, 96, 94], file: "Franz Beckenbauer 2006 06 17.jpg", credit: "Hans Buch (cropped by afrank99) · Wikimedia Commons / Public domain", creditUrl: "https://creativecommons.org/publicdomain/mark/1.0/" },
    { id: "cruyff", name: "克鲁伊夫", english: "JOHAN CRUYFF", number: "14", category: "传奇球星", archetype: "用想法改变比赛的人", summary: "你喜欢先理解规则，再找到重新组织局面的方法。好点子不只为自己服务；它能让整支队伍换一种方式踢得更好。", tags: ["战术想象", "主动创造", "团队思维"], profile: [98, 90, 97, 98, 93], file: "Johan Cruijff (1974).jpg", credit: "Rob Mieremet / Anefo · Wikimedia Commons / CC0", creditUrl: "https://creativecommons.org/publicdomain/zero/1.0/" }
  ]
};
